web/router.ex
defmodule Library.Router do
  use Library.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Library do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/loans", BookController, :index
    get "/loans/:id", BookController, :extend
  end

  # Other scopes may use custom stacks.
  # scope "/api", Library do
  #   pipe_through :api
  # end
end

lib/library/endpoint.ex
defmodule Library.Endpoint do
  use Phoenix.Endpoint, otp_app: :library

  socket "/socket", Library.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :library, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_library_key",
    signing_salt: "lO+14fIb"

  plug Library.Router
end

lib/library/repo.ex
defmodule Library.Repo do
  use Ecto.Repo, otp_app: :library
end

web/models/book.ex
defmodule Library.Book do
    use Library.Web, :model

    schema "book" do
        field :title, :string
        field :code, :string
        field :start_date, :date
        field :due_date, :date
        field :times_extended, :integer

        timestamps()
    end

    def changeset(struct, params \\ %{}) do
        struct
        |> cast(params, [:title, :code, :start_date, :due_date, :times_extended])
        |> unique_constraint(:title, title: :book_title_index, message: "This book already exists.")
    end
end

web/controllers/book_controller.ex
defmodule Library.BookController do
    use Library.Web, :controller

    alias Ecto.{Changeset}
    alias Library.{Repo,Book}
  
    def index(conn, _params) do
      books = Repo.all(from b in Book)

      conn = conn |> put_status(200)
      render conn, "loans.html", books: books
    end

    def extend(conn, %{"id" => book_id}) do
        book = Repo.get(Book, book_id)
        books = Repo.all(from b in Book)

        if book.times_extended == 4 do
            conn = conn
             |> put_status(400)
             |> put_flash(:error, "Extension rejected")

             render conn, "loans.html", books: books
        else
            if book.code == "A" do
                due_date = book.due_date
                date = Date.add(due_date, 7)
    
                post = Ecto.Changeset.change book, due_date: date
                Repo.update post
            end
    
            if book.code == "B" do
                due_date = book.due_date
                date = Date.add(due_date, 14)
    
                post = Ecto.Changeset.change book, due_date: date
                Repo.update post
            end
    
            if book.code == "C" do
                due_date = book.due_date
                date = Date.add(due_date, 21)
    
                post = Ecto.Changeset.change book, due_date: date
                Repo.update post
            end
    
            times = book.times_extended
            times = times + 1

            post = Ecto.Changeset.change book, times_extended: times
            Repo.update post

            conn = conn 
                |> put_status(200)
                |> put_flash(:info, "Extension accepted")
    
            render conn, "loans.html", books: books
        end
    end
  end
  

web/controllers/page_controller.ex
defmodule Library.PageController do
  use Library.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/book_view.ex
defmodule Library.BookView do
    use Library.Web, :view
  end
  

web/views/error_view.ex
defmodule Library.ErrorView do
  use Library.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Library.LayoutView do
  use Library.Web, :view
end

web/views/page_view.ex
defmodule Library.PageView do
  use Library.Web, :view
end

web/templates/book/loans.html.eex
<h2>My book loans</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th>Start Date</th>
      <th>Due Date</th>
      <th>Time Extended</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
<%= for book <- @books do %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.code %></td>
      <td><%= book.start_date %></td>
      <td><%= book.due_date %></td>
      <td><%= book.times_extended %></td>
      <td>
        <span>
          <%= link "Extend", to: book_path(@conn, :extend, book.id), id: book.id, class: "btn btn-default btn-xs" %>
        </span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Library!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div id="library-app">
  <loans></loans>
</div>